%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This matlab script demonstrates how to perform the calculations to
% reproduce Figure 2 from:
%   Pitzel et al (2024) "Derivations of the Total Radiation Belt Electron
%   Content", JGR - Space Physics
% showing TRBEC integrated in (E,alpha,L*) space in March 2013.
% This script downloads the data, performs the calculations to find
% the TRBEC integrated over various L* and energy ranges and saves
% the results for further analysis.
% See script "Example_Fig_2_plot.m" to plot Figure 2 from the intermediate
% files generated by this script.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                SETUP
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% start and stop days (inclues full half orbits that occured within the period)
epoch_start = datenum(2013,02,27);
epoch_stop = datenum(2013,03,19);

%integration bounds
energy_min = 0.1;
energy_max = 0.3;
Lstar_min = 3.5;
Lstar_max = 5;


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Step 1: Download and install the CDF Patch from GSFC:
%    https://cdf.gsfc.nasa.gov/html/matlab_cdf_patch.html
% and the Matlab Curve Fitting Toolbox.
% You may need to execute something like this on startup after installing the CDF tools:
%   addpath 'C:\matlab_cdf390_patch'
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp("Step 1: Checking CDF Patch install.")
try
    spdfcdfinfo();
catch
    disp("Error using spdfcdf. Please install the CDF Patch from GSFC.")
    disp("   See:  https://cdf.gsfc.nasa.gov/html/matlab_cdf_patch.html")
    disp("   If it's already installed, check your path. Try:")
    disp("      addpath 'C:\matlab_cdf390_patch'")
    return
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Step 2: Download the MagEIS data files.
% Required data are the L3 combined MagEIS files available at:
%     https://rbsp-ect.newmexicoconsortium.org/data_pub/rbspb/mageis/level3/pitchangle/
% with filename rbspx_rel04_ect-mageis-L3_yyyymmdd_vX.X.X.cdf.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp("Step 2: Downloading data.")

% Directory in which to store the MagEIS data
PSD_directory  = 'PSD_data/';
flux_directory = 'flux_data/';
warning('off')
mkdir(flux_directory);
warning('on') 
download_data(PSD_directory,flux_directory,epoch_start,epoch_stop)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Step 3: Calculate the TRBEC over the given integration bounds.
% This will also create the differential content files in directory
% DC_E_PA with filename like DC_E_PA_rbspa_20130301_033832.mat.
% The differential content files give the TRBEC integrated over various L*
% and energy ranges and can be used for further analysis.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp("Step 3: Calculating TRBEC.")
format longE

% Results will be saved to this directory:
DC_directory = 'DC_E_PA/';
PSD_directory = 'PSD_data/';
warning('off') 
mkdir(DC_directory);
warning('on') 

%compute the TRBEC over desired time interval for given integration bounds
tic
[TRBEC_rbspa,epoch_rbspa] = TRBEC_energy_pitch_angle_wrapper(flux_directory,DC_directory,epoch_start,epoch_stop,'rbspa',energy_min,energy_max,Lstar_min,Lstar_max,PSD_directory);
[TRBEC_rbspb,epoch_rbspb] = TRBEC_energy_pitch_angle_wrapper(flux_directory,DC_directory,epoch_start,epoch_stop,'rbspb',energy_min,energy_max,Lstar_min,Lstar_max,PSD_directory);
toc

%get rid of TRBEC = 0
epoch_rbspa(TRBEC_rbspa == 0) = [];epoch_rbspb(TRBEC_rbspb == 0) = [];
TRBEC_rbspa(TRBEC_rbspa == 0) = [];TRBEC_rbspb(TRBEC_rbspb == 0) = [];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Step 4: Plot the result.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp("Step4: Plotting.")

semilogy(epoch_rbspa,TRBEC_rbspa,'r')
hold on
semilogy(epoch_rbspb,TRBEC_rbspb,'b')

datetick('x','dd-mmm','keeplimits')
ylabel('TRBEC')
xlim([epoch_start epoch_stop+1])
legend('RBSP A','RBSP B')

%add bounds to TRBEC plot
dim = [0.15, 0.6, 0.3, 0.3];
str = {[strcat('E =',32,num2str(energy_min),32,'to',32,num2str(energy_max),' MeV')],['\alpha_{eq} = \alpha_{eq,LC} to \pi/2'],[strcat('L* =',32,num2str(Lstar_min),32,'to',32,num2str(Lstar_max))]};
annotation('textbox',dim,'String',str,'FitBoxToText','on');
