%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This matlab script demonstrates how to perform the calculations to
% reproduce Figure 1 from:
%   Pitzel et al (2024) "Derivations of the Total Radiation Belt Electron
%   Content", JGR - Space Physics
% showing TRBEC integrated in (mu,K,L*) space in March 2013.
% This script downloads the data, performs the calculations to find
% the TRBEC integrated over various L* and energy ranges and saves
% the results for further analysis.
% See script "Example_Fig_1_plot.m" to plot Figure 1 from the intermediate
% files generated by this script.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
tic

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                SETUP
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% start and stop days (inclues full half orbits that occured within the period)
epoch_start = datenum(2013,02,27);
epoch_stop = datenum(2013,03,20);

%integration bounds
mu_min = 50;
mu_max = 200;
Lstar_min = 3.5;
Lstar_max = 5;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Step 1: Download and install the CDF Patch from GSFC:
%    https://cdf.gsfc.nasa.gov/html/matlab_cdf_patch.html
% and the Matlab Curve Fitting Toolbox.
% You may need to execute something like this on startup after installing the CDF tools:
%   addpath 'C:\matlab_cdf390_patch'
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp("Step 1: Checking CDF Patch install.")
try
    spdfcdfinfo();
catch
    disp("Error using spdfcdf. Please install the CDF Patch from GSFC.")
    disp("   See:  https://cdf.gsfc.nasa.gov/html/matlab_cdf_patch.html")
    disp("   If it's already installed, check your path. Try:")
    disp("      addpath 'C:\matlab_cdf390_patch'")
    return
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Step 2: Download the MagEIS data files.
% Required data are the L3 combined MagEIS files available at:
%     https://rbsp-ect.newmexicoconsortium.org/data_pub/rbspb/mageis/level3/pitchangle/
% with filename rbspx_rel04_ect-mageis-L3_yyyymmdd_vX.X.X.cdf
% and the PSD data files from:
%     https://rbspgway.jhuapl.edu/rTools/psdN/lib/php/getCDF.php?cli=%20-T%201362096000%20-E%2086400%20-S%20rbspa%20-A%20TS04
% with filename PSD_rbspx_mageis_yyyyddd.cdf
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp("Step 2: Downloading data.")

PSD_directory  = 'PSD_data/';
flux_directory = 'flux_data/';
DC_directory = 'DC_mu_K/';

warning('off')
mkdir(flux_directory);
mkdir(PSD_directory);
warning('on') 
download_data(PSD_directory,flux_directory,epoch_start,epoch_stop)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Step 3: Calculate the TRBEC over the given integration bounds.
% This will also create the differential content files in directory
% DC_mu_K with filename like DC_mu_K_rbspa_20130301_033832.mat.
% The differential content files give the TRBEC integrated over all
% K and within various L* and mu ranges. These files can be used for
% further analysis and plotting, including reproducing Figure 1 of the
% paper.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp("Step 3: Calculating TRBEC.")
format longE
warning('off')

%compute the TRBEC over desired time interval for given integration bounds
[TRBEC_rbspa,epoch_rbspa] = TRBEC_mu_K_wrapper(PSD_directory,flux_directory,DC_directory,epoch_start,epoch_stop,'rbspa',mu_min,mu_max,Lstar_min,Lstar_max);
[TRBEC_rbspb,epoch_rbspb] = TRBEC_mu_K_wrapper(PSD_directory,flux_directory,DC_directory,epoch_start,epoch_stop,'rbspb',mu_min,mu_max,Lstar_min,Lstar_max);

%remove TRBEC = 0
epoch_rbspa(TRBEC_rbspa == 0) = [];epoch_rbspb(TRBEC_rbspb == 0) = [];
TRBEC_rbspa(TRBEC_rbspa == 0) = [];TRBEC_rbspb(TRBEC_rbspb == 0) = [];

%remove outliers ('mean' defines outliers as points that are three standard deviations from the mean).
[TRBEC_rbspa_cleaned,rbspa_cleaned_indices] = rmoutliers(TRBEC_rbspa);[TRBEC_rbspb_cleaned,rbspb_cleaned_indices] = rmoutliers(TRBEC_rbspb);
epoch_rbspa_cleaned = epoch_rbspa(rbspa_cleaned_indices == 0); epoch_rbspb_cleaned = epoch_rbspb(rbspb_cleaned_indices == 0); 
toc

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Step 4: Plot the result.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp("Step4: Plotting.")

semilogy(epoch_rbspa_cleaned,TRBEC_rbspa_cleaned,'r-')
hold on
semilogy(epoch_rbspb_cleaned,TRBEC_rbspb_cleaned,'b-')
datetick('x','dd-mmm','keeplimits')
ylabel('TRBEC')
xlim([epoch_start epoch_stop+1])
%ylim([10^23 10^29])
legend('RBSP A','RBSP B')

%add bounds to TRBEC plot
dim = [0.15, 0.6, 0.3, 0.3];
str = {[strcat('\mu =',32,num2str(mu_min),32,'to',32,num2str(mu_max),' MeV')],['\alpha_{eq} = \alpha_{eq,LC} to \pi/2'],[strcat('L* =',32,num2str(Lstar_min),32,'to',32,num2str(Lstar_max))]};
annotation('textbox',dim,'String',str,'FitBoxToText','on');